### ISSUE TITLE
Unable to disable name suffix hash

### ISSUE THREAD

**Issue by teutonet** [Agilicus/kustomize-sops#4]
kustomize-sops plugin always appends the name suffix hash even when it's disabled by global generator options:

**kustomization.yaml**:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

generators:
- kustomization-secrets.yaml
```

All references of the Secret are named without the hash suffix and they don't get updated.

So therefore it would be nice to have the ability to disable name suffix hash.
